import React, { useEffect } from "react";
import { FaShieldAlt, FaChild, FaExternalLinkAlt } from "react-icons/fa";

const PrivacyPolicy = () => {
  useEffect(() => {
    // Ensure scrolling to the top of the document when the component is mounted
    window.scrollTo({
      top: 0,
      behavior: "auto", // You can use "auto" for instant scroll
    });

    // As a fallback, scroll the root element
    document.documentElement.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  }, []);
  return (
    <div className="bg-black text-white min-h-screen p-6 pt-20">
      {/* Privacy Policy Content */}
      <div className="max-w-5xl mx-auto space-y-10">
        {/* Title */}
        <h1 className="text-4xl font-bold text-center mb-10">Privacy Policy</h1>
        <h2>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You. We use Your Personal data to provide and improve the
          Service. By using the Service, You agree to the collection and use of
          information in accordance with this Privacy Policy.
        </h2>
        {/* Section: Interpretation and Definitions */}
        <section>
          <h2 className="text-2xl font-bold text-orange-500 mb-4">
            Interpretation and Definitions
          </h2>
          <h2 className="text-xl font-bold text-orange-500 mb-4">
            Interpretation
          </h2>
          <p className="mb-4">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. These definitions shall have
            the same meaning regardless of whether they appear in singular or
            plural.
          </p>
          <h2 className="text-xl font-bold text-orange-500 mb-4">
            Interpretation
          </h2>
          <ul className="list-disc ml-6 space-y-2">
            <li>
              Account means a unique account created for You to access our
              Service or parts of our Service.
            </li>
            <li>
              Affiliate means an entity that controls, is controlled by or is
              under common control with a party, where “control” means ownership
              of 50% or more of the shares, equity interest or other securities
              entitled to vote for election of directors or other managing
              authority.
            </li>
            <li>
              Company (referred to as either “the Company”, “We”, “Us” or “Our”
              in this Agreement) refers to Sapna Sangeeta.
            </li>
            <li>
              Cookies are small files that are placed on Your computer, mobile
              device or any other device by a website, containing the details of
              Your browsing history on that website among its many uses.
            </li>
            <li>Country refers to: Madhya Pradesh, India</li>
            <li>
              Device means any device that can access the Service such as a
              computer, a cellphone or a digital tablet.
            </li>
            <li>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </li>
            <li>Service refers to the Website.</li>
            <li>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company. It refers to third-party
              companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to
              perform services related to the Service or to assist the Company
              in analyzing how the Service is used.
            </li>
            <li>
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              Website refers to Sapna Sangeeta, accessible from
              https://sapnasangeeta.com/
            </li>
            <li>
              You means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </li>
          </ul>
        </section>

        {/* Section: Collecting and Using Your Personal Data */}
        <section>
          <h2 className="text-4xl font-bold text-orange-500 mb-4">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="text-2xl font-semibold text-white mb-2">
            Types of Data Collected
          </h3>
          <span className="text-orange-500 text-2xl font-semibold">
            Usage Data <br /> <br />
          </span>
          <h2>
            Usage Data is collected automatically when using the Service.
            <br /> <br />
            Usage Data may include information such as Your Device’s Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data. <br /> <br />
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data. <br /> <br />
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </h2>
        </section>

        <section>
          <span className="text-orange-500 text-2xl font-semibold">
            Tracking Technologies and Cookies
            <br /> <br />
          </span>
          <p>
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service. The
            technologies We use may include:
          </p>
          <ul className="list-disc ml-6 space-y-2">
            <li>
              Cookies or Browser Cookies. A cookie is a small file placed on
              Your Device. You can instruct Your browser to refuse all Cookies
              or to indicate when a Cookie is being sent. However, if You do not
              accept Cookies, You may not be able to use some parts of our
              Service. Unless you have adjusted Your browser setting so that it
              will refuse Cookies, our Service may use Cookies.
            </li>
            <li>
              Web Beacons. Certain sections of our Service and our emails may
              contain small electronic files known as web beacons (also referred
              to as clear gifs, pixel tags, and single-pixel gifs) that permit
              the Company, for example, to count users who have visited those
              pages or opened an email and for other related website statistics
              (for example, recording the popularity of a certain section and
              verifying system and server integrity).
            </li>
          </ul>
          <h2>
            Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies
            remain on Your personal computer or mobile device when You go
            offline, while Session Cookies are deleted as soon as You close Your
            web browser.
          </h2>
          <h2>
            We use both Session and Persistent Cookies for the purposes set out
            below:
          </h2>
          <ul className="list-disc ml-6 space-y-2">
            <li>
              Necessary / Essential Cookies Type: Session Cookies Administered
              by: Us Purpose: These Cookies are essential to provide You with
              services available through the Website and to enable You to use
              some of its features. They help to authenticate users and prevent
              fraudulent use of user accounts. Without these Cookies, the
              services that You have asked for cannot be provided, and We only
              use these Cookies to provide You with those services.
            </li>
            <li>
              Cookies Policy / Notice Acceptance Cookies Type: Persistent
              Cookies Administered by: Us Purpose: These Cookies identify if
              users have accepted the use of cookies on the Website.
            </li>
            <li>
              Functionality Cookies Type: Persistent Cookies Administered by: Us
              Purpose: These Cookies allow us to remember choices You make when
              You use the Website, such as remembering your login details or
              language preference. The purpose of these Cookies is to provide
              You with a more personal experience and to avoid You having to
              re-enter your preferences every time You use the Website.
            </li>
          </ul>
          <h2>
            For more information about the cookies we use and your choices
            regarding cookies, please visit our Cookies Policy or the Cookies
            section of our Privacy Policy.
          </h2>
        </section>

        {/* Section: Security of Your Personal Data */}
        <section>
          <h2 className="text-2xl font-bold text-orange-500 mb-4 flex items-center">
            <FaShieldAlt className="mr-2" /> Security of Your Personal Data
          </h2>
          <p>
            The security of your Personal Data is important to us. We use
            commercially acceptable means to protect your data but cannot
            guarantee its absolute security.
          </p>
          <ul className="list-disc ml-6 space-y-2">
            <li>
              With Service Providers: We may share Your personal information
              with Service Providers to monitor and analyze the use of our
              Service, to contact You.
            </li>
            <li>
              For business transfers: We may share or transfer Your personal
              information in connection with, or during negotiations of, any
              merger, sale of Company assets, financing, or acquisition of all
              or a portion of Our business to another company.
            </li>
            <li>
              With Affiliates: We may share Your information with Our
              affiliates, in which case we will require those affiliates to
              honor this Privacy Policy. Affiliates include Our parent company
              and any other subsidiaries, joint venture partners or other
              companies that We control or that are under common control with
              Us.
            </li>
            <li>
              With business partners: We may share Your information with Our
              business partners to offer You certain products, services or
              promotions.
            </li>
            <li>
              With other users: when You share personal information or otherwise
              interact in the public areas with other users, such information
              may be viewed by all users and may be publicly distributed
              outside.
            </li>
            <li>
              With Your consent: We may disclose Your personal information for
              any other purpose with Your consent.
            </li>
          </ul>
        </section>

        {/* Section: Children's Privacy */}
        <section>
          <h2 className="text-2xl font-bold text-orange-500 mb-4 flex items-center">
            <FaChild className="mr-2" /> Retention of Your Personal Data
          </h2>

          <ul className="list-disc ml-6 space-y-2">
            <li>
              The Company will also retain Usage Data for internal analysis
              purposes. Usage Data is generally retained for a shorter period of
              time, except when this data is used to strengthen the security or
              to improve the functionality of Our Service, or We are legally
              obligated to retain this data for longer time periods.
            </li>
          </ul>

          <p>
            We may share Your personal information in the following situations:
          </p>
        </section>

        {/* Section: Links to Other Websites */}
        <section>
          <h2 className="text-2xl font-bold text-orange-500 mb-4 flex items-center">
            <FaExternalLinkAlt className="mr-2" /> Links to Other Websites
          </h2>
          <p>
            Our Service may contain links to other websites that are not
            operated by us. We strongly advise you to review the Privacy Policy
            of every site you visit. We have no control over and assume no
            responsibility for the content, privacy policies, or practices of
            any third-party websites.
          </p>
        </section>

        {/* Section: Changes to This Privacy Policy */}
        <section>
          <h2 className="text-2xl font-bold text-orange-500 mb-4">
            Changes to This Privacy Policy
          </h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </p>
        </section>

        {/* Section: Contact Us */}
        <section>
          <h2 className="text-2xl font-bold text-orange-500 mb-4">
            Contact Us
          </h2>
          If you have any questions about this Privacy Policy, you can contact
          us by email.
        </section>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
